# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/josefonseca/Documents/thesis/verilog/dot_prod/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/josefonseca/Documents/thesis/verilog/dot_prod/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /home/josefonseca/Documents/thesis/verilog/dot_prod/dot_prod.v
synth_design -top dot_prod -part xc7z020clg484-1
write_checkpoint -noxdef dot_prod.dcp
catch { report_utilization -file dot_prod_utilization_synth.rpt -pb dot_prod_utilization_synth.pb }
