# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/josefonseca/Documents/thesis/verilog/tanh/tanh_synth/tanh_synth.cache/wt [current_project]
set_property parent.project_path /home/josefonseca/Documents/thesis/verilog/tanh/tanh_synth/tanh_synth.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /home/josefonseca/Documents/thesis/verilog/tanh/tanh_synth/tanh_synth.srcs/sources_1/imports/tanh/tanh.v
read_xdc /home/josefonseca/Documents/thesis/verilog/tanh/tanh_synth/tanh_synth.srcs/constrs_1/new/tanh_const.xdc
set_property used_in_implementation false [get_files /home/josefonseca/Documents/thesis/verilog/tanh/tanh_synth/tanh_synth.srcs/constrs_1/new/tanh_const.xdc]

synth_design -top tanh -part xc7z020clg484-1
write_checkpoint -noxdef tanh.dcp
catch { report_utilization -file tanh_utilization_synth.rpt -pb tanh_utilization_synth.pb }
