# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/josefonseca/Documents/thesis/verilog/gate/Synth_gate/Synth_gate.cache/wt [current_project]
set_property parent.project_path /home/josefonseca/Documents/thesis/verilog/gate/Synth_gate/Synth_gate.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/josefonseca/Documents/thesis/verilog/gate/dot_prod.v
  /home/josefonseca/Documents/thesis/verilog/gate/gate.v
}
read_xdc /home/josefonseca/Documents/thesis/verilog/gate/Synth_gate/Synth_gate.srcs/constrs_1/new/gate_constr.xdc
set_property used_in_implementation false [get_files /home/josefonseca/Documents/thesis/verilog/gate/Synth_gate/Synth_gate.srcs/constrs_1/new/gate_constr.xdc]

synth_design -top gate -part xc7z020clg484-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5 -mode out_of_context
write_checkpoint -noxdef gate.dcp
catch { report_utilization -file gate_utilization_synth.rpt -pb gate_utilization_synth.pb }
